steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/phoenix', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/phoenix']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'phoenix'
    - '--image'
    - 'gcr.io/$PROJECT_ID/phoenix'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--memory'
    - '1Gi'
    - '--cpu'
    - '1'
    - '--timeout'
    - '3600'
    - '--concurrency'
    - '8'
    - '--max-instances'
    - '100'
    - '--service-account'
    - 'phoenix-service-account@phoenix-project-386.iam.gserviceaccount.com'
    - '--update-secrets'
    - 'GEMINI_API_KEY=phoenix-gemini-api-key:latest,SECRET_KEY=phoenix-secret-key:latest,GOOGLE_API_KEY=phoenix-google-api-key:latest,GOOGLE_SEARCH_ENGINE_ID=phoenix-search-engine-id:latest,NEWSDATA_API_KEY=phoenix-newsdata-api-key:latest,KAGGLE_USERNAME=phoenix-kaggle-username:latest,KAGGLE_KEY=phoenix-kaggle-key:latest,CLAUDE_API_KEY=phoenix-claude-api-key:latest,GROK_API_KEY=phoenix-grok-api-key:latest,OPENAI_API_KEY=phoenix-openai-api-key:latest,GOOGLE_CLIENT_ID=phoenix-google-client-id:latest,GOOGLE_CLIENT_SECRET=phoenix-google-client-secret:latest,FIREBASE_API_KEY=phoenix-firebase-api-key:latest,R2_ACCESS_KEY_ID=phoenix-r2-access-key-id:latest,R2_SECRET_ACCESS_KEY=phoenix-r2-secret-access-key:latest,R2_ENDPOINT_URL=phoenix-r2-endpoint-url:latest,R2_BUCKET_NAME=phoenix-r2-bucket-name:latest,R2_PUBLIC_URL=phoenix-r2-public-url:latest,STRIPE_SECRET_KEY=STRIPE_SECRET_KEY_PROD:latest,STRIPE_WEBHOOK_SECRET=STRIPE_WEBHOOK_SECRET_PROD:latest,STRIPE_PUBLISHABLE_KEY=STRIPE_PUBLISHABLE_KEY_PROD:latest,STRIPE_TOKEN_STARTER_PRICE_ID=STRIPE_TOKEN_STARTER_PRICE_ID:latest,STRIPE_TOKEN_POPULAR_PRICE_ID=STRIPE_TOKEN_POPULAR_PRICE_ID:latest,STRIPE_TOKEN_PRO_PRICE_ID=STRIPE_TOKEN_PRO_PRICE_ID:latest,STRIPE_TOKEN_CREATOR_PRICE_ID=STRIPE_TOKEN_CREATOR_PRICE_ID:latest'
    - '--update-env-vars'
    - 'DEFAULT_MODEL=gemini-1.5-flash-8b,FALLBACK_MODEL=gemini-1.5-flash,FLASK_ENV=production,GOOGLE_CLOUD_PROJECT=phoenix-project-386,PRODUCTION_URL=https://phoenix-234619602247.us-central1.run.app,APP_BASE_URL=https://phoenix-234619602247.us-central1.run.app,VIDEO_STORAGE_BUCKET=phoenix-videos'
    - '--max-instances'
    - '1'

images:
  - 'gcr.io/$PROJECT_ID/phoenix'

# Add options for logging when using a service account
options:
  logging: CLOUD_LOGGING_ONLY
