steps:
  # Build the container image for dev
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/phoenix-dev', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/phoenix-dev']
  
  # Deploy container image to Cloud Run (DEV environment)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'phoenix-dev'
    - '--image'
    - 'gcr.io/$PROJECT_ID/phoenix-dev'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--service-account'
    - 'phoenix-service-account@phoenix-project-386.iam.gserviceaccount.com'
    - '--memory'
    - '1Gi'
    - '--cpu'
    - '1'
    - '--max-instances'
    - '5'
    - '--concurrency'
    - '10'
    - '--update-secrets'
    - 'GEMINI_API_KEY=phoenix-gemini-api-key:latest,SECRET_KEY=phoenix-secret-key:latest,GOOGLE_API_KEY=phoenix-google-api-key:latest,GOOGLE_SEARCH_ENGINE_ID=phoenix-search-engine-id:latest,NEWSDATA_API_KEY=phoenix-newsdata-api-key:latest,KAGGLE_USERNAME=phoenix-kaggle-username:latest,KAGGLE_KEY=phoenix-kaggle-key:latest,CLAUDE_API_KEY=phoenix-claude-api-key:latest,GROK_API_KEY=phoenix-grok-api-key:latest'
    - '--update-env-vars'
    - 'DEFAULT_MODEL=gemini-1.5-flash-8b,FALLBACK_MODEL=gemini-1.5-flash,FLASK_ENV=development,SESSION_COOKIE_SECURE=true'

images:
  - 'gcr.io/$PROJECT_ID/phoenix-dev'

# Add options for logging when using a service account
options:
  logging: CLOUD_LOGGING_ONLY