steps:
  # ========================================
  # STEP 1: Build Frontend (React + Vite)
  # ========================================
  
  # Install frontend dependencies
  - name: 'node:18'
    dir: 'frontend/soho'
    entrypoint: 'npm'
    args: ['ci']  # 'ci' is faster than 'install' in CI environments
  
  # Build frontend (creates dist/ folder)
  - name: 'node:18'
    dir: 'frontend/soho'
    entrypoint: 'npm'
    args: ['run', 'build']
  
  # Copy built frontend to Flask static folder (so it's included in Docker image)
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        mkdir -p static/momo
        cp -r frontend/soho/dist/* static/momo/
        echo "Frontend built and copied to static/momo/"
        ls -la static/momo/
  
  # ========================================
  # STEP 2: Build & Deploy Backend (Flask)
  # ========================================
  
  # Pull previous images for Docker layer caching (speeds up builds by 70%)
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'docker pull gcr.io/$PROJECT_ID/phoenix:latest || exit 0'

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'docker pull gcr.io/$PROJECT_ID/image-generation-job:latest || exit 0'

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'docker pull gcr.io/$PROJECT_ID/video-generation-job:latest || exit 0'

  # Build the main phoenix container image (with caching)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--cache-from=gcr.io/$PROJECT_ID/phoenix:latest'
      - '-t'
      - 'gcr.io/$PROJECT_ID/phoenix'
      - '.'
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/phoenix']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'phoenix'
    - '--image'
    - 'gcr.io/$PROJECT_ID/phoenix'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--memory'
    - '1Gi'
    - '--cpu'
    - '1'
    - '--timeout'
    - '3600'
    - '--concurrency'
    - '8'
    - '--max-instances'
    - '100'
    - '--service-account'
    - 'phoenix-service-account@phoenix-project-386.iam.gserviceaccount.com'
    - '--update-secrets'
    - 'GEMINI_API_KEY=phoenix-gemini-api-key:latest,SECRET_KEY=phoenix-secret-key:latest,GOOGLE_API_KEY=phoenix-google-api-key:latest,GOOGLE_SEARCH_ENGINE_ID=phoenix-search-engine-id:latest,NEWSDATA_API_KEY=phoenix-newsdata-api-key:latest,KAGGLE_USERNAME=phoenix-kaggle-username:latest,KAGGLE_KEY=phoenix-kaggle-key:latest,CLAUDE_API_KEY=phoenix-claude-api-key:latest,GROK_API_KEY=phoenix-grok-api-key:latest,OPENAI_API_KEY=phoenix-openai-api-key:latest,GOOGLE_CLIENT_ID=phoenix-google-client-id:latest,GOOGLE_CLIENT_SECRET=phoenix-google-client-secret:latest,FIREBASE_API_KEY=phoenix-firebase-api-key:latest,R2_ACCESS_KEY_ID=phoenix-r2-access-key-id:latest,R2_SECRET_ACCESS_KEY=phoenix-r2-secret-access-key:latest,R2_ENDPOINT_URL=phoenix-r2-endpoint-url:latest,R2_BUCKET_NAME=phoenix-r2-bucket-name:latest,R2_PUBLIC_URL=phoenix-r2-public-url:latest,STRIPE_SECRET_KEY=STRIPE_SECRET_KEY_PROD:latest,STRIPE_WEBHOOK_SECRET=STRIPE_WEBHOOK_SECRET_PROD:latest,STRIPE_PUBLISHABLE_KEY=STRIPE_PUBLISHABLE_KEY_PROD:latest,STRIPE_TOKEN_STARTER_PRICE_ID=STRIPE_TOKEN_STARTER_PRICE_ID:latest,STRIPE_TOKEN_POPULAR_PRICE_ID=STRIPE_TOKEN_POPULAR_PRICE_ID:latest,STRIPE_TOKEN_PRO_PRICE_ID=STRIPE_TOKEN_PRO_PRICE_ID:latest,STRIPE_TOKEN_CREATOR_PRICE_ID=STRIPE_TOKEN_CREATOR_PRICE_ID:latest,SOCIAL_TOKEN_ENCRYPTION_KEY=phoenix-social-token-encryption-key:latest'
    - '--update-env-vars'
    - 'DEFAULT_MODEL=gemini-1.5-flash-8b,FALLBACK_MODEL=gemini-1.5-flash,FLASK_ENV=production,GOOGLE_CLOUD_PROJECT=phoenix-project-386,PRODUCTION_URL=https://phoenix-234619602247.us-central1.run.app,APP_BASE_URL=https://phoenix-234619602247.us-central1.run.app,VIDEO_STORAGE_BUCKET=phoenix-videos'
    - '--max-instances'
    - '1'
    - '--clear-vpc-connector'

  # Build Image Generation Job (with caching)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--cache-from=gcr.io/$PROJECT_ID/image-generation-job:latest'
      - '-t'
      - 'gcr.io/$PROJECT_ID/image-generation-job'
      - '-f'
      - 'jobs/image_generation_job/Dockerfile'
      - '.'

  # Push Image Generation Job
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/image-generation-job']

  # Deploy Image Generation Job (Cloud Run Job - not Service)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'jobs'
      - 'deploy'
      - 'image-generation-job'
      - '--image=gcr.io/$PROJECT_ID/image-generation-job'
      - '--region=us-central1'
      - '--cpu=1'
      - '--memory=512Mi'
      - '--task-timeout=300'
      - '--max-retries=2'
      - '--service-account=phoenix-service-account@phoenix-project-386.iam.gserviceaccount.com'
      - '--update-secrets=GEMINI_API_KEY=phoenix-gemini-api-key:latest,R2_ACCESS_KEY_ID=phoenix-r2-access-key-id:latest,R2_SECRET_ACCESS_KEY=phoenix-r2-secret-access-key:latest,R2_ENDPOINT_URL=phoenix-r2-endpoint-url:latest,R2_BUCKET_NAME=phoenix-r2-bucket-name:latest,R2_PUBLIC_URL=phoenix-r2-public-url:latest'
      - '--update-env-vars=GOOGLE_CLOUD_PROJECT=phoenix-project-386'

  # Build Video Generation Job (with caching)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--cache-from=gcr.io/$PROJECT_ID/video-generation-job:latest'
      - '-t'
      - 'gcr.io/$PROJECT_ID/video-generation-job'
      - '-f'
      - 'jobs/video_generation_job/Dockerfile'
      - '.'

  # Push Video Generation Job
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/video-generation-job']

  # Deploy Video Generation Job (Cloud Run Job - Large Machine)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'jobs'
      - 'deploy'
      - 'video-generation-job'
      - '--image=gcr.io/$PROJECT_ID/video-generation-job'
      - '--region=us-central1'
      - '--cpu=2'
      - '--memory=4Gi'
      - '--task-timeout=600'
      - '--max-retries=2'
      - '--service-account=phoenix-service-account@phoenix-project-386.iam.gserviceaccount.com'
      - '--labels=app=phoenix,service=video-worker,env=prod'
      - '--update-secrets=GEMINI_API_KEY=phoenix-gemini-api-key:latest,R2_ACCESS_KEY_ID=phoenix-r2-access-key-id:latest,R2_SECRET_ACCESS_KEY=phoenix-r2-secret-access-key:latest,R2_ENDPOINT_URL=phoenix-r2-endpoint-url:latest,R2_BUCKET_NAME=phoenix-r2-bucket-name:latest,R2_PUBLIC_URL=phoenix-r2-public-url:latest'
      - '--update-env-vars=GOOGLE_CLOUD_PROJECT=phoenix-project-386'

images:
  - 'gcr.io/$PROJECT_ID/phoenix'
  - 'gcr.io/$PROJECT_ID/image-generation-job'
  - 'gcr.io/$PROJECT_ID/video-generation-job'

# Add options for logging when using a service account
options:
  logging: CLOUD_LOGGING_ONLY
