"""
Website Stats Service

Service for managing global website statistics and analytics.
"""
import logging
from firebase_admin import firestore
from datetime import datetime
from typing import Dict, Optional

logger = logging.getLogger(__name__)

class WebsiteStatsService:
    def __init__(self):
        self.db = firestore.client()
        self.stats_doc_id = "global_stats"
        self.stats_collection = "website_stats"

    def initialize_stats(self) -> Dict:
        """Initialize website stats document."""
        try:
            # Create initial stats document
            stats_data = {
                'total_videos_generated': 0,
                'total_images_generated': 0,
                'total_video_seconds_generated': 0,
                'last_updated': firestore.SERVER_TIMESTAMP,
                'created_at': firestore.SERVER_TIMESTAMP,
                'version': 7
            }

            # Set the document (will overwrite if exists)
            self.db.collection(self.stats_collection).document(self.stats_doc_id).set(stats_data)

            logger.info("Initialized website stats")
            return stats_data

        except Exception as e:
            logger.error(f"Error initializing website stats: {e}")
            return {}

    def increment_videos_generated(self, amount: int = 1) -> bool:
        """Increment the total videos generated counter (for Video Generator feature).

        Args:
            amount: Number of videos to add (default 1)
        """
        try:
            stats_ref = self.db.collection(self.stats_collection).document(self.stats_doc_id)
            stats_ref.update({
                'total_videos_generated': firestore.Increment(amount),
                'last_updated': firestore.SERVER_TIMESTAMP
            })
            logger.info(f"Incremented total_videos_generated by {amount}")
            return True
        except Exception as e:
            logger.error(f"Error incrementing videos generated: {e}")
            return False

    def increment_images_generated(self, amount: int = 1) -> bool:
        """Increment the total images generated counter (for Image Generator feature).

        Args:
            amount: Number of images to add (default 1)
        """
        try:
            stats_ref = self.db.collection(self.stats_collection).document(self.stats_doc_id)
            stats_ref.update({
                'total_images_generated': firestore.Increment(amount),
                'last_updated': firestore.SERVER_TIMESTAMP
            })
            logger.info(f"Incremented total_images_generated by {amount}")
            return True
        except Exception as e:
            logger.error(f"Error incrementing images generated: {e}")
            return False

    def increment_video_seconds_generated(self, seconds: int = 8) -> bool:
        """Increment the total video seconds generated counter (for Reel Maker feature).

        Args:
            seconds: Number of seconds to add (default 8 for typical reel clip)
        """
        try:
            stats_ref = self.db.collection(self.stats_collection).document(self.stats_doc_id)
            stats_ref.update({
                'total_video_seconds_generated': firestore.Increment(seconds),
                'last_updated': firestore.SERVER_TIMESTAMP
            })
            logger.info(f"Incremented total_video_seconds_generated by {seconds}")
            return True
        except Exception as e:
            logger.error(f"Error incrementing video seconds generated: {e}")
            return False

    def get_website_stats(self) -> Dict:
        """Get current website statistics."""
        try:
            stats_doc = self.db.collection(self.stats_collection).document(self.stats_doc_id).get()

            if stats_doc.exists:
                return stats_doc.to_dict()
            else:
                # Initialize if doesn't exist
                return self.initialize_stats()

        except Exception as e:
            logger.error(f"Error fetching website stats: {e}")
            return {}

    def get_stats_for_display(self) -> Dict:
        """Get formatted stats for display in UI."""
        stats = self.get_website_stats()

        if not stats:
            return {
                'videos_generated': '0',
                'images_generated': '0',
                'video_seconds_generated': '0',
                'last_updated': 'Never'
            }

        return {
            'videos_generated': f"{stats.get('total_videos_generated', 0):,}",
            'images_generated': f"{stats.get('total_images_generated', 0):,}",
            'video_seconds_generated': f"{stats.get('total_video_seconds_generated', 0):,}",
            'last_updated': stats.get('last_updated', 'Unknown')
        }
