# Master Cloud Build configuration for ALL Cloud Run Jobs
# This builds and deploys all job types in the jobs/ directory
# Useful for bulk deployments or ensuring all jobs are in sync

steps:
  # ====================================
  # Video Stitching Job
  # ====================================
  
  # Build stitching job image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-stitching-job'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/reel-stitching-job:latest'
      - '-t'
      - 'gcr.io/$PROJECT_ID/reel-stitching-job:$BUILD_ID'
      - '-f'
      - 'jobs/video_stitching/Dockerfile'
      - '.'
  
  # Push stitching job images
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-stitching-job-latest'
    waitFor: ['build-stitching-job']
    args: ['push', 'gcr.io/$PROJECT_ID/reel-stitching-job:latest']
  
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-stitching-job-build'
    waitFor: ['build-stitching-job']
    args: ['push', 'gcr.io/$PROJECT_ID/reel-stitching-job:$BUILD_ID']

  # Deploy stitching job
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-stitching-job'
    waitFor: ['push-stitching-job-latest']
    entrypoint: gcloud
    args:
      - 'run'
      - 'jobs'
      - 'update'
      - 'reel-stitching-job'
      - '--image'
      - 'gcr.io/$PROJECT_ID/reel-stitching-job:latest'
      - '--region'
      - 'us-central1'
      - '--cpu'
      - '2'
      - '--memory'
      - '4Gi'
      - '--timeout'
      - '900'
      - '--max-retries'
      - '2'

  # ====================================
  # Add future jobs here following the same pattern
  # ====================================
  
  # Example for a future job (commented out):
  # - name: 'gcr.io/cloud-builders/docker'
  #   id: 'build-future-job'
  #   args:
  #     - 'build'
  #     - '-t'
  #     - 'gcr.io/$PROJECT_ID/future-job:latest'
  #     - '-f'
  #     - 'jobs/future_job/Dockerfile'
  #     - '.'

images:
  - 'gcr.io/$PROJECT_ID/reel-stitching-job:latest'
  - 'gcr.io/$PROJECT_ID/reel-stitching-job:$BUILD_ID'
  # Add future job images here

timeout: '3600s'  # 1 hour for multiple jobs

options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
  logging: CLOUD_LOGGING_ONLY
  env:
    - 'DOCKER_BUILDKIT=1'
